### ISSUE TITLE
update broke.  `Unhandled "error" event`

### ISSUE THREAD

**Issue by jedierikb** [corneliusio/gulp-svgo#2]
Alas, something in the update has broken gulp-svgo for me.
```
gulp.task('svg', function( opts ) {
  var svg = gulp.src( [srcpath + 'assets/app/svg/*'] )
    .pipe(svgo({

    }))
    .pipe( gulp.dest(buildsvgpath) );

  return svg;
});



```
```
[14:45:32] Starting 'svg'...
events.js:187
      throw err;
      ^

Error: Unhandled "error" event. ([object Object])
    at Transform.emit (events.js:185:19)
    at Transform.onerror (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at emitOne (events.js:115:13)
    at Transform.emit (events.js:210:7)
    at onwriteError (_stream_writable.js:383:10)
    at onwrite (_stream_writable.js:406:5)
    at afterTransform (_stream_transform.js:102:3)
    at TransformState.afterTransform (_stream_transform.js:75:12)
    at svgo.optimize.result (/Users/project/node_modules/gulp-svgo/index.js:25:24)
    at optimizeOnceCallback (/Users/project/node_modules/gulp-svgo/node_modules/svgo/lib/svgo.js:44:17)
    at /Users/project/node_modules/gulp-svgo/node_modules/svgo/lib/svgo.js:65:9
    at SAXParser.sax.onend (/Users/project/node_modules/gulp-svgo/node_modules/svgo/lib/svgo/svg2js.js:156:13)
    at emit (/Users/project/node_modules/sax/lib/sax.js:640:35)
    at end (/Users/project/node_modules/sax/lib/sax.js:683:5)
    at SAXParser.write (/Users/project/node_modules/sax/lib/sax.js:991:14)
    at SAXParser.close (/Users/project/node_modules/sax/lib/sax.js:157:38)
    at module.exports (/Users/project/node_modules/gulp-svgo/node_modules/svgo/lib/svgo/svg2js.js:169:28)
    at module.exports.SVGO._optimizeOnce (/Users/project/node_modules/gulp-svgo/node_modules/svgo/lib/svgo.js:56:5)
    at module.exports.SVGO.optimize (/Users/project/node_modules/gulp-svgo/node_modules/svgo/lib/svgo.js:49:11)
    at Transform.stream._transform (/Users/project/node_modules/gulp-svgo/index.js:22:18)
    at Transform._read (_stream_transform.js:190:10)
    at Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:371:12)
    at writeOrBuffer (_stream_writable.js:357:5)
    at Transform.Writable.write (_stream_writable.js:274:11)
    at write (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:105:13)
    at DestroyableTransform.emit (events.js:207:7)
    at emitReadable_ (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (/Users/project/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:105:13)
    at DestroyableTransform.emit (events.js:207:7)
    at emitReadable_ (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/Users/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /Users/project/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:490:3)

```

**Comment by corneliusio** [comment]
Sorry about that, issue should be resolved now. Be sure to update to the latest version and give it another shot.

**Comment by jedierikb** [comment]
Much thanks, that fixes it!
